// lingo3d-vue/src/components/editor/Editor.vue
<script setup lang="ts">
import "lingo3d/lib/editor"

const props = defineProps({
    blockKeyboard: { type: Boolean, default: true },
    blockMouse: { type: Boolean, default: true }
})
</script>

<template>
    <lingo3d-editor :block-keyboard="props.blockKeyboard" :block-mouse="props.blockMouse" />
</template>

// lingo3d-react/src/components/Editor.tsx
import React from "react"
import "lingo3d/lib/editor/Editor"

interface EditorProps {
    blockKeyboard?: boolean,
    blockMouse?: boolean
}

const Editor: React.FC<EditorProps> = ({ blockKeyboard = true, blockMouse = true }) => {
    return (
        //@ts-ignore
        <lingo3d-editor block-keyboard={blockKeyboard} block-mouse={blockMouse}  />
    )
}

export default Editor
