// lingo3d-vue/src/components/Stats.vue
<script setup lang="ts">
import { PropType, ref, toRaw, watchEffect } from "vue"
import { onBeforeRender } from "lingo3d/lib/events/onBeforeRender"
import { onAfterRender } from "lingo3d/lib/events/onAfterRender"
import StatsJS from "stats.js"

const props = defineProps({
  mode: {
    type: String as PropType<"fps" | "time" | "memory">,
    default: "fps"
  }
})
const divRef = ref<HTMLDivElement>()

watchEffect((cleanup) => {
  const div = toRaw(divRef.value)
  if (!div) return

  const stats = new StatsJS()
  stats.showPanel(props.mode === "fps" ? 0 : props.mode === "time" ? 1 : 2)
  div.appendChild(stats.dom)

  const beforeHandle = onBeforeRender(() => stats.begin())
  const afterHandle = onAfterRender(() => stats.end())

  cleanup(() => {
    beforeHandle.cancel()
    afterHandle.cancel()
  })
})
</script>

<template>
  <div ref="divRef" />
</template>

// lingo3d-react/src/components/Stats.tsx
import React, { useLayoutEffect, useRef } from "react"
import { onBeforeRender } from "lingo3d/lib/events/onBeforeRender"
import { onAfterRender } from "lingo3d/lib/events/onAfterRender"
import StatsJS from "stats.js"

type StatsProps = {
    mode?: "fps" | "time" | "memory"
}

const Stats: React.FC<StatsProps> = ({ mode = "fps" }) => {
    const divRef = useRef<HTMLDivElement>(null)

    useLayoutEffect(() => {
        const div = divRef.current
        if (!div) return

        const stats = new StatsJS()
        stats.showPanel(mode === "fps" ? 0 : mode === "time" ? 1 : 2)
        div.appendChild(stats.dom)

        const beforeHandle = onBeforeRender(() => stats.begin())
        const afterHandle = onAfterRender(() => stats.end())

        return () => {
            beforeHandle.cancel()
            afterHandle.cancel()
        }
    }, [])

    return (
        <div ref={divRef} />
    )
}

export default Stats
