// lingo3d-vue/src/components/display/lights/AreaLight.vue
<script lang="ts">
export default { inheritAttrs: false }
</script>
<script setup lang="ts">
import { AreaLight } from "lingo3d"
import useManager from "../../../hooks/useManager"
import areaLightProps from "../../../props/areaLightProps"

const props = defineProps(areaLightProps)
const manager = useManager(props, AreaLight)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/lights/AreaLight.tsx
import React from "react"
import { AreaLight as GameAreaLight } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { AreaLightProps } from "../../../props"

const AreaLight = React.forwardRef<GameAreaLight, AreaLightProps>((p, ref) => {
  const manager = useManager(p, ref, GameAreaLight)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default AreaLight
