// lingo3d-vue/src/components/display/lights/DefaultSkyLight.vue
<script setup lang="ts">
import { DefaultSkyLight } from "lingo3d"
import useManager from "../../../hooks/useManager"
import defaultSkyLightProps from "../../../props/defaultSkyLightProps"

const props = defineProps(defaultSkyLightProps)
const manager = useManager(props, DefaultSkyLight)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/lights/DefaultSkyLight.tsx
import React from "react"
import { DefaultSkyLight as GameDefaultSkyLight } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { DefaultSkyLightProps } from "../../../props/DefaultSkyLightProps"

const DefaultSkyLight = React.forwardRef<
  GameDefaultSkyLight,
  DefaultSkyLightProps
>((p, ref) => {
  const manager = useManager(p, ref, GameDefaultSkyLight)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default DefaultSkyLight
