// lingo3d-vue/src/components/display/lights/SkyLight.vue
<script setup lang="ts">
import { SkyLight } from "lingo3d"
import useManager from "../../../hooks/useManager"
import skyLightProps from "../../../props/skyLightProps"

const props = defineProps(skyLightProps)
const manager = useManager(props, SkyLight)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/lights/SkyLight.tsx
import React from "react"
import { SkyLight as GameSkyLight } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { SkyLightProps } from "../../../props"

const SkyLight = React.forwardRef<GameSkyLight, SkyLightProps>((p, ref) => {
    const manager = useManager(p, ref, GameSkyLight)
    return <ParentContext.Provider value={manager}>{p.children}</ParentContext.Provider>
})

export default SkyLight
