// lingo3d-vue/src/components/display/lights/SpotLight.vue
<script lang="ts">
export default { inheritAttrs: false }
</script>
<script setup lang="ts">
import { SpotLight } from "lingo3d"
import useManager from "../../../hooks/useManager"
import spotLightProps from "../../../props/spotLightProps"

const props = defineProps(spotLightProps)
const manager = useManager(props, SpotLight)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/lights/SpotLight.tsx
import React from "react"
import { SpotLight as GameSpotLight } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { SpotLightProps } from "../../../props/SpotLightProps"

const SpotLight = React.forwardRef<GameSpotLight, SpotLightProps>((p, ref) => {
  const manager = useManager(p, ref, GameSpotLight)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default SpotLight
