// lingo3d-react/src/components/editor/Toolbar.tsx
import React from "react"
import LingoToolbar from "lingo3d/lib/editor/Toolbar"
import useEditor from "../../hooks/useEditor"

type ButtonOptions = {
  hidden?: boolean
  onClick?: () => void
}

interface ToolbarProps {
  buttons?: {
    openJSON?: ButtonOptions
    exportJSON?: ButtonOptions
    exportReact?: ButtonOptions
    exportVue?: ButtonOptions
  }
}

const Toolbar: React.FC<ToolbarProps> = (props) => {
  const divRef = useEditor(LingoToolbar, props)

  return <div ref={divRef} className="lingo3d-ui" style={{ height: "100%" }} />
}

export default Toolbar

// lingo3d-vue/src/components/editor/Toolbar.vue
<script setup lang="ts">
import Toolbar from "lingo3d/lib/editor/Toolbar"
import { PropType } from "vue"
import useEditor from "../../hooks/useEditor"

type ButtonOptions = {
  hidden?: boolean
  onClick?: () => void
}

const props = defineProps({
  buttons: {
    type: Object as PropType<{
      openJSON?: ButtonOptions
      exportJSON?: ButtonOptions
      exportReact?: ButtonOptions
      exportVue?: ButtonOptions
    }>,
    default: {}
  }
})

const divRef = useEditor(Toolbar, props)
</script>

<template>
  <div ref="divRef" class="lingo3d-ui" style="height: 100%" />
</template>
