// lingo3d-vue/src/components/logical/Find.vue
<script setup lang="ts">
import FoundManager from "lingo3d/lib/display/core/FoundManager"
import Loaded from "lingo3d/lib/display/core/Loaded"
import ObjectManager from "lingo3d/lib/display/core/ObjectManager"
import { foundDefaults } from "lingo3d/lib/interface/IFound"
import {
  inject,
  ref,
  watchEffect,
  computed,
  Ref,
  provide,
  toRaw,
  PropType
} from "vue"
import useDiffProps from "../../hooks/useDiffProps"
import { applyChanges } from "../../hooks/useManager"
import foundProps from "../../props/foundProps"
import processDefaults from "../../props/utils/processDefaults"

const props = defineProps({
  ...foundProps,
  onLoad: Function as PropType<(found: FoundManager) => void>
})

const parentRef = inject<Ref<ObjectManager | Loaded> | undefined>(
  "parent",
  undefined
)
const managerRef = ref<FoundManager>()
provide("parent", managerRef)

watchEffect((onCleanUp) => {
  const { name } = props
  const parent = toRaw(parentRef?.value)
  if (!parent || !name) return

  if ("loaded" in parent) {
    const handle = parent.loaded.then(() => {
      managerRef.value = parent.find(name)
    })
    return onCleanUp(() => {
      handle.cancel()
    })
  }
  managerRef.value = parent.find(name)
})

const paused = computed(() => !managerRef.value)
const defaults = processDefaults(foundDefaults)
const diff = useDiffProps(props, defaults, paused)
applyChanges(managerRef, undefined, diff, defaults)

watchEffect(() => {
  const manager = toRaw(managerRef.value)
  manager && props.onLoad?.(manager)
})
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/logical/Find.tsx
import FoundManager from "lingo3d/lib/display/core/FoundManager"
import React, { useContext, useLayoutEffect, useState } from "react"
import useDiffProps from "../../hooks/useDiffProps"
import { applyChanges, ParentContext } from "../../hooks/useManager"
import { FoundProps } from "../../props"

const Find = React.forwardRef<
  FoundManager,
  FoundProps & { onLoad?: (manager: FoundManager) => void }
>(({ name, onLoad, ...p }, ref) => {
  const parent = useContext(ParentContext)
  const [manager, setManager] = useState<any>()

  useLayoutEffect(() => {
    if (!parent || !name) return

    if ("loaded" in parent) {
      const handle = parent.loaded.then(() => {
        setManager(parent.find(name))
      })
      return () => {
        handle.cancel()
      }
    }
    setManager(parent.find(name))
  }, [parent, name])

  const [changed, removed] = useDiffProps(p, !manager)
  manager && applyChanges(manager, changed, removed)

  useLayoutEffect(() => {
    if (!ref || !manager) return

    if (typeof ref === "function") ref(manager)
    else ref.current = manager
  }, [ref, manager])

  useLayoutEffect(() => {
    manager && onLoad?.(manager)
  }, [manager])

  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default Find
