// lingo3d-vue/src/components/logical/FindAll.vue
<script setup lang="ts">
import FoundManager from "lingo3d/lib/display/core/FoundManager"
import Loaded from "lingo3d/lib/display/core/Loaded"
import ObjectManager from "lingo3d/lib/display/core/ObjectManager"
import { foundDefaults } from "lingo3d/lib/interface/IFound"
import {
  inject,
  ref,
  watchEffect,
  computed,
  Ref,
  provide,
  toRaw,
  PropType
} from "vue"
import useDiffProps from "../../hooks/useDiffProps"
import { applyChanges } from "../../hooks/useManager"
import foundProps from "../../props/foundProps"
import processDefaults from "../../props/utils/processDefaults"

const props = defineProps({
  ...foundProps,
  name: {
    required: true,
    type: [String, RegExp]
  },
  onLoad: Function as PropType<(found: Array<FoundManager>) => void>
})

const parentRef = inject<Ref<ObjectManager | Loaded> | undefined>(
  "parent",
  undefined
)
const managerRef = ref<Array<FoundManager>>()
provide("parent", managerRef)

let nameOld = toRaw(props.name)
const _name = computed(() => {
  const name = toRaw(props.name)
  if (
    typeof name !== "string" &&
    typeof nameOld !== "string" &&
    name.toString() === nameOld.toString()
  )
    return nameOld

  nameOld = name
  return name
})

watchEffect((onCleanUp) => {
  const name = toRaw(_name.value)
  const parent = toRaw(parentRef?.value)
  if (!parent || !name) return

  if ("loaded" in parent) {
    const handle = parent.loaded.then(() => {
      managerRef.value = parent.findAll(name)
    })
    return onCleanUp(() => {
      handle.cancel()
    })
  }
  managerRef.value = parent.findAll(name)
})

const paused = computed(() => !managerRef.value)
const defaults = processDefaults(foundDefaults)
const diff = useDiffProps(props, defaults, paused)
applyChanges(managerRef, undefined, diff, defaults)

watchEffect(() => {
  const manager = toRaw(managerRef.value)
  manager && props.onLoad?.(manager)
})
</script>

<template></template>

// lingo3d-react/src/components/logical/FindAll.tsx
import FoundManager from "lingo3d/lib/display/core/FoundManager"
import React, {
  useContext,
  useLayoutEffect,
  useMemo,
  useRef,
  useState
} from "react"
import useDiffProps from "../../hooks/useDiffProps"
import { applyChanges, ParentContext } from "../../hooks/useManager"
import { FoundProps } from "../../props"

const FindAll = React.forwardRef<
  Array<FoundManager>,
  Omit<FoundProps, "name"> & {
    name: string | RegExp
    onLoad?: (managers: Array<FoundManager>) => void
  }
>(({ name, onLoad, ...p }, ref) => {
  const parent = useContext(ParentContext)
  const [managers, setManagers] = useState<Array<any>>()

  const nameOld = useRef(name)
  const _name = useMemo(() => {
    if (
      typeof name !== "string" &&
      typeof nameOld !== "string" &&
      name.toString() === nameOld.toString()
    )
      return nameOld.current

    nameOld.current = name
    return name
  }, [name])

  useLayoutEffect(() => {
    if (!parent || !_name) return

    if ("loaded" in parent) {
      const handle = parent.loaded.then(() => {
        setManagers(parent.findAll(_name))
      })
      return () => {
        handle.cancel()
      }
    }
    setManagers(parent.findAll(_name))
  }, [parent, _name])

  const [changed, removed] = useDiffProps(p, !managers)
  if (managers)
    for (const manager of managers) applyChanges(manager, changed, removed)

  useLayoutEffect(() => {
    if (!ref || !managers) return

    if (typeof ref === "function") ref(managers)
    else ref.current = managers
  }, [ref, managers])

  useLayoutEffect(() => {
    managers && onLoad?.(managers)
  }, [managers])

  return null
})

export default FindAll
