// lingo3d-vue/src/logical/Find.vue
<script setup lang="ts">
import ObjectManager from "lingo3d/lib/display/core/ObjectManager"
import { objectManagerDefaults } from "lingo3d/lib/interface/IObjectManager";
import { inject, ref, watchEffect, computed } from "vue"
import useDiffProps from "../hooks/useDiffProps"
import managerProps from "../props/managerProps"

const props = defineProps({
    ...managerProps,
    onLoad: Function
})

const parent: any = inject("parent", undefined)
const managerRef = ref<ObjectManager>()

watchEffect(onCleanUp => {
    const { name } = props
    if (!parent || !name) return
    
    if ("loadedResolvable" in parent){
        //@ts-ignore
        const handle = parent.loadedResolvable.then(() => managerRef.value = parent.find(name))
        return onCleanUp(() => {
            handle.cancel()
        })
    }
    managerRef.value = parent.find(name)
})

const paused = computed(() => !managerRef.value)
const diff = useDiffProps(props, objectManagerDefaults, paused)

watchEffect(() => {
    const manager = managerRef.value
    if (!manager) return

    for (const [key, value] of diff.value)
        //@ts-ignore
        manager[key] = value ?? objectManagerDefaults[key]
})

defineExpose(managerRef)

watchEffect(() => {
    managerRef.value && props.onLoad?.()
})

</script>

<template>
    <slot />
</template>

// lingo3d-react/src/components/logical/Find.tsx
import SimpleObjectManager from "lingo3d/lib/display/core/SimpleObjectManager"
import React, { useContext, useLayoutEffect, useState } from "react"
import useDiffProps from "../../hooks/useDiffProps"
import { applyChanges, ParentContext } from "../../hooks/useManager"
import { ManagerProps } from "../../Props"

const Find = React.forwardRef<SimpleObjectManager, ManagerProps & { onLoad?: () => void }>(({ name, onLoad, ...p }, ref) => {
    const parent = useContext(ParentContext)
    const [manager, setManager] = useState<any>()

    useLayoutEffect(() => {
        if (!parent || !name) return

        if ("loadedResolvable" in parent){
            //@ts-ignore
            const handle = parent.loadedResolvable.then(() => setManager(parent.find(name)))
            return () => {
                handle.cancel()
            }
        }
        setManager(parent.find(name))

    }, [parent, name])

    const [changed, removed] = useDiffProps(p, !manager)
    manager && applyChanges(manager, changed, removed)

    useLayoutEffect(() => {
        if (!ref || !manager) return

        if (typeof ref === "function")
            ref(manager)
        else
            ref.current = manager
            
    }, [ref, manager])

    useLayoutEffect(() => {
        manager && onLoad?.()
    }, [manager])

    return <ParentContext.Provider value={manager}>{p.children}</ParentContext.Provider>
})

export default Find
