// lingo3d-react/src/components/Editor.tsx
import React, { useLayoutEffect, useRef } from "react"
import { Editor as LingoEditor } from "lingo3d"

interface EditorProps {
}

const Editor: React.FC<EditorProps> = () => {
    const divRef = useRef<HTMLDivElement>(null)

    useLayoutEffect(() => {
        const el = divRef.current
        if (!el) return

        const editor = new LingoEditor()
        el.appendChild(editor)
        
        return () => {
            editor.remove()
        }
    }, [])

    return (
        <div ref={divRef} />
    )
}

export default Editor

// lingo3d-vue/src/components/Editor.vue
<script setup lang="ts">
import { ref, watchEffect } from "vue"
import { Editor as LingoEditor } from "lingo3d"

const divRef = ref<HTMLDivElement>()

watchEffect(onCleanUp => {
    const el = divRef.value
    if (!el) return

    const editor = new LingoEditor()
    el.appendChild(editor)

    onCleanUp(() => {
        editor.remove()
    })
})

</script>

<template>
    <div ref="divRef" />
</template>
