// lingo3d-vue/src/components/display/cameras/Camera.vue
<script lang="ts">
export default { inheritAttrs: false }
</script>
<script setup lang="ts">
import { Camera } from "lingo3d"
import useManager from "../../../hooks/useManager"
import cameraProps from "../../../props/cameraProps"

const props = defineProps(cameraProps)
const manager = useManager(props, Camera)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/cameras/Camera.tsx
import React from "react"
import { Camera as GameCamera } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { CameraProps } from "../../../props"

const Camera = React.forwardRef<GameCamera, CameraProps>((p, ref) => {
  const manager = useManager(p, ref, GameCamera)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default Camera
