// lingo3d-vue/src/components/display/cameras/FirstPersonCamera.vue
<script setup lang="ts">
import { FirstPersonCamera } from "lingo3d"
import useManager from "../../../hooks/useManager"
import firstPersonCameraProps from "../../../props/firstPersonCameraProps"

const props = defineProps(firstPersonCameraProps)
const manager = useManager(props, FirstPersonCamera)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/cameras/FirstPersonCamera.tsx
import React from "react"
import { FirstPersonCamera as GameFirstPersonCamera } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { FirstPersonCameraProps } from "../../../props/FirstPersonCameraProps"

const FirstPersonCamera = React.forwardRef<
  GameFirstPersonCamera,
  FirstPersonCameraProps
>((p, ref) => {
  const manager = useManager(p, ref, GameFirstPersonCamera)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default FirstPersonCamera
