// lingo3d-vue/src/components/display/cameras/ThirdPersonCamera.vue
<script setup lang="ts">
import { ThirdPersonCamera } from "lingo3d"
import useManager from "../../../hooks/useManager"
import thirdPersonCameraProps from "../../../props/thirdPersonCameraProps"

const props = defineProps(thirdPersonCameraProps)
const manager = useManager(props, ThirdPersonCamera)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/cameras/ThirdPersonCamera.tsx
import React from "react"
import { ThirdPersonCamera as GameThirdPersonCamera } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { ThirdPersonCameraProps } from "../../../props"

const ThirdPersonCamera = React.forwardRef<GameThirdPersonCamera, ThirdPersonCameraProps>((p, ref) => {
    const manager = useManager(p, ref, GameThirdPersonCamera)
    return <ParentContext.Provider value={manager}>{p.children}</ParentContext.Provider>
})

export default ThirdPersonCamera
