// lingo3d-react/src/components/ui/Joystick.tsx
import React from "react"
import { Joystick as GameJoystick } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { JoystickProps } from "../../props/JoystickProps"

const Joystick = React.forwardRef<GameJoystick, JoystickProps>((p, ref) => {
  const manager = useManager(p, ref, GameJoystick)
  return <ParentContext.Provider value={manager} />
})

export default Joystick

// lingo3d-vue/src/components/ui/Joystick.vue
<script setup lang="ts">
import { Joystick } from "lingo3d"
import useManager from "../../hooks/useManager"
import joystickProps from "../../props/joystickProps"

const props = defineProps(joystickProps)
const manager = useManager(props, Joystick)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
