// lingo3d-react/src/components/ui/Reticle.tsx
import React from "react"
import { Reticle as GameReticle } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { ReticleProps } from "../../props/ReticleProps"

const Reticle = React.forwardRef<GameReticle, ReticleProps>((p, ref) => {
  const manager = useManager(p, ref, GameReticle)
  return <ParentContext.Provider value={manager} />
})

export default Reticle

// lingo3d-vue/src/components/ui/Reticle.vue
<script setup lang="ts">
import { Reticle } from "lingo3d"
import useManager from "../../hooks/useManager"
import reticleProps from "../../props/reticleProps"

const props = defineProps(reticleProps)
const manager = useManager(props, Reticle)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
