// lingo3d-react/src/components/display/primitives/Cylinder.tsx
import React from "react"
import { Cylinder as GameCylinder } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { CylinderProps } from "../../../props/CylinderProps"

const Cylinder = React.forwardRef<GameCylinder, CylinderProps>((p, ref) => {
  const manager = useManager(p, ref, GameCylinder)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default Cylinder

// lingo3d-vue/src/components/display/primitives/Cylinder.vue
<script setup lang="ts">
import { Cylinder } from "lingo3d"
import useManager from "../../../hooks/useManager"
import cylinderProps from "../../../props/cylinderProps"

const props = defineProps(cylinderProps)
const manager = useManager(props, Cylinder)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
