// packages/lingo3d-react/src/components/display/primitives/Plane.tsx
import React from "react"
import { Plane as GamePlane } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { PrimitiveProps } from "../../../Props"

const Plane = React.forwardRef<GamePlane, PrimitiveProps>((p, ref) => {
    const manager = useManager(p, ref, GamePlane)
    return <ParentContext.Provider value={manager}>{p.children}</ParentContext.Provider>
})

export default Plane

// lingo3d-vue/src/components/display/primitives/Plane.vue
<script setup lang="ts">
import { Plane } from "lingo3d"
import useManager from "../../../hooks/useManager"
import primitiveProps from "../../../props/primitiveProps"

const props = defineProps(primitiveProps)
const manager = useManager(props, Plane)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
