// lingo3d-vue/src/components/display/primitives/Circle.vue
<script setup lang="ts">
import { Circle } from "lingo3d"
import useManager from "../../../hooks/useManager"
import circleProps from "../../../props/circleProps"

const props = defineProps(circleProps)
const manager = useManager(props, Circle)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/primitives/Circle.tsx
import React from "react"
import { Circle as GameCircle } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { CircleProps } from "../../../props/CircleProps"

const Circle = React.forwardRef<GameCircle, CircleProps>((p, ref) => {
  const manager = useManager(p, ref, GameCircle)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default Circle
