// lingo3d-vue/src/components/display/primitives/Cone.vue
<script setup lang="ts">
import { Cone } from "lingo3d"
import useManager from "../../../hooks/useManager"
import coneProps from "../../../props/coneProps"

const props = defineProps(coneProps)
const manager = useManager(props, Cone)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/primitives/Cone.tsx
import React from "react"
import { Cone as GameCone } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { ConeProps } from "../../../props/ConeProps"

const Cone = React.forwardRef<GameCone, ConeProps>((p, ref) => {
  const manager = useManager(p, ref, GameCone)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default Cone
