// lingo3d-vue/src/components/display/primitives/Octahedron.vue
<script setup lang="ts">
import { Octahedron } from "lingo3d"
import useManager from "../../../hooks/useManager"
import primitiveProps from "../../../props/primitiveProps"

const props = defineProps(primitiveProps)
const manager = useManager(props, Octahedron)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/primitives/Octahedron.tsx
import React from "react"
import { Octahedron as GameOctahedron } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { PrimitiveProps } from "../../../props"

const Octahedron = React.forwardRef<GameOctahedron, PrimitiveProps>(
  (p, ref) => {
    const manager = useManager(p, ref, GameOctahedron)
    return (
      <ParentContext.Provider value={manager}>
        {p.children}
      </ParentContext.Provider>
    )
  }
)

export default Octahedron
