// lingo3d-vue/src/components/display/primitives/Sphere.vue
<script setup lang="ts">
import { Sphere } from "lingo3d"
import useManager from "../../../hooks/useManager"
import primitiveProps from "../../../props/primitiveProps"

const props = defineProps(primitiveProps)
const manager = useManager(props, Sphere)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/primitives/Sphere.tsx
import React from "react"
import { Sphere as GameSphere } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { PrimitiveProps } from "../../../props"

const Sphere = React.forwardRef<GameSphere, PrimitiveProps>((p, ref) => {
    const manager = useManager(p, ref, GameSphere)
    return <ParentContext.Provider value={manager}>{p.children}</ParentContext.Provider>
})

export default Sphere
