// lingo3d-vue/src/components/display/primitives/Tetrahedron.vue
<script setup lang="ts">
import { Tetrahedron } from "lingo3d"
import useManager from "../../../hooks/useManager"
import primitiveProps from "../../../props/primitiveProps"

const props = defineProps(primitiveProps)
const manager = useManager(props, Tetrahedron)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/primitives/Tetrahedron.tsx
import React from "react"
import { Tetrahedron as GameTetrahedron } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { PrimitiveProps } from "../../../props"

const Tetrahedron = React.forwardRef<GameTetrahedron, PrimitiveProps>(
  (p, ref) => {
    const manager = useManager(p, ref, GameTetrahedron)
    return (
      <ParentContext.Provider value={manager}>
        {p.children}
      </ParentContext.Provider>
    )
  }
)

export default Tetrahedron
