// lingo3d-vue/src/components/display/primitives/Torus.vue
<script setup lang="ts">
import { Torus } from "lingo3d"
import useManager from "../../../hooks/useManager"
import torusProps from "../../../props/torusProps"

const props = defineProps(torusProps)
const manager = useManager(props, Torus)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/primitives/Torus.tsx
import React from "react"
import { Torus as GameTorus } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { TorusProps } from "../../../props/TorusProps"

const Torus = React.forwardRef<GameTorus, TorusProps>((p, ref) => {
  const manager = useManager(p, ref, GameTorus)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default Torus
