// lingo3d-react/src/components/logical/Frame.tsx
import { clientToWorld, Group as LingoGroup, onBeforeRender } from "lingo3d"
import React, { useLayoutEffect, useRef } from "react"
import Group from "../display/Group"

interface FrameProps {
  className?: string
  style?: React.CSSProperties
  distance?: number
  children?: any
}

const Frame: React.FC<FrameProps> = ({
  children,
  className,
  style,
  distance = 500
}) => {
  const elRef = useRef<HTMLDivElement>(null)
  const groupRef = useRef<LingoGroup>(null)

  useLayoutEffect(() => {
    const el = elRef.current
    const group = groupRef.current
    if (!el || !group) return

    const handle = onBeforeRender(() => {
      const { left, top, width, height } = el.getBoundingClientRect()
      const clientX = left + width * 0.5
      const clientY = top + height * 0.5
      group.placeAt(clientToWorld(clientX, clientY, distance))
    })
    return () => {
      handle.cancel()
    }
  }, [distance])

  return (
    <div ref={elRef} className={className} style={style}>
      <Group ref={groupRef}>{children}</Group>
    </div>
  )
}

export default Frame

// lingo3d-vue/src/components/logical/Frame.vue
<script setup lang="ts">
import { ref, toRaw, watchEffect } from "vue"
import Group from "../display/Group.vue"
import { clientToWorld, Group as LingoGroup, onBeforeRender } from "lingo3d"

const props = defineProps({
  distance: {
    type: Number,
    default: 500
  }
})

const elRef = ref<HTMLDivElement>()
const groupRef = ref<LingoGroup>()

watchEffect((cleanup) => {
  const el = toRaw(elRef.value)
  const group = toRaw(groupRef.value)
  if (!el || !group) return

  const { distance } = props

  const handle = onBeforeRender(() => {
    const { left, top, width, height } = el.getBoundingClientRect()
    const clientX = left + width * 0.5
    const clientY = top + height * 0.5
    group.placeAt(clientToWorld(clientX, clientY, distance))
  })
  cleanup(() => {
    handle.cancel()
  })
})
</script>

<template>
  <div ref="elRef">
    <Group ref="groupRef">
      <slot />
    </Group>
  </div>
</template>
