// lingo3d-react/src/components/editor/TweakPane/index.tsx
import React, { useEffect } from "react"
import { Pane } from "tweakpane"
import addInputs from "./addInputs"
import useInit from "./useInit"

type CustomEditorProps = {
  children?: JSX.Element | Array<JSX.Element>
}

const CustomEditor = ({ children }: CustomEditorProps) => {
  const elRef = useInit()

  const _children: Array<JSX.Element | undefined> = Array.isArray(children)
    ? children
    : [children]

  useEffect(() => {
    const el = elRef.current
    if (!el || !_children.length) return

    const pane = new Pane({ container: el })

    const params = Object.fromEntries(
      _children
        .filter((child) => child!.props?.name)
        .map((child) => [
          child!.props.name,
          child!.props.values ? child!.props : child!.props.value
        ])
    )
    const onChange = Object.fromEntries(
      _children
        .filter((child) => child!.props?.name)
        .map((child) => [child!.props.name, child!.props.onChange])
    )
    addInputs(pane, "inputs", params, (name, value) => onChange[name]?.(value))

    return () => {
      pane.dispose()
    }
  }, [_children])

  return (
    <div
      ref={elRef}
      className="lingo3d-ui"
      style={{
        width: 300,
        background: "rgb(40, 41, 46)",
        position: "absolute",
        top: 0,
        right: 0,
        zIndex: 1
      }}
    />
  )
}

export default CustomEditor

// lingo3d-vue/src/components/editor/TweakPane/index.vue
<script setup lang="ts">
import { Pane } from "tweakpane"
import { provide, ref, toRaw, watchEffect } from "vue"
import addInputs from "./addInputs"
import useInit from "./useInit"

const elRef = useInit()

const _childrenRef = ref<Array<any>>([])
provide("_childrenRef", _childrenRef)

watchEffect((cleanup) => {
  const el = toRaw(elRef.value)
  const _children = toRaw(_childrenRef.value)
  if (!el || !_children.length) return

  const pane = new Pane({ container: el })

  const params = Object.fromEntries(
    _children
      .filter((child) => child.name)
      .map((child) => [child.name, child.values ? child : child.value])
  )
  const onChange = Object.fromEntries(
    _children
      .filter((child) => child.name)
      .map((child) => [child.name, child.onChange])
  )
  addInputs(pane, "inputs", params, (name, value) => onChange[name]?.(value))

  cleanup(() => {
    pane.dispose()
  })
})
</script>

<template>
  <div
    ref="elRef"
    className="lingo3d-ui"
    style="
      width: 300px;
      background: rgb(40, 41, 46);
      position: absolute;
      top: 0px;
      right: 0px;
      z-index: 1;
    "
  >
    <slot />
  </div>
</template>
