// lingo3d-vue/src/logical/HTML/index.vue
<script setup lang="ts">
import { pull } from "@lincode/utils"
import ObjectManager from "lingo3d/lib/display/core/ObjectManager"
import { inject, useSlots, VNode, watchEffect } from "vue"
import { elements } from "./build"
import render from "./render"

const parent: any = inject("parent", undefined)
const slots = useSlots()

watchEffect(onCleanUp => {
    if (!parent) return

    const children = slots.default?.()
    if (!children) return

    const pair: [Array<VNode>, ObjectManager] = [children, parent]
    
    elements.push(pair)
    render()

    onCleanUp(() => {
        pull(elements, pair)
        render()
    })
})

    

</script>

<template>
    <slot />
</template>

// packages/lingo3d-react/src/components/logical/HTML/index.tsx
import React, { useContext, useLayoutEffect } from "react"
import { ParentContext } from "../../../hooks/useManager"
import { pull } from "lodash"
import ObjectManager from "lingo3d/lib/display/core/ObjectManager"
import render from "./render17"
import { elements } from "./build"

interface HTMLProps {
    parent?: any,
    children: React.ReactNode
}

const HTML: React.FC<HTMLProps> = ({ children }) => {
    const parent = useContext(ParentContext)

    useLayoutEffect(() => {
        if (!parent) return

        const pair: [React.ReactNode, ObjectManager] = [children, parent]

        elements.push(pair)
        render()

        return () => {
            pull(elements, pair)
            render()
        }
    }, [parent])

    return null
}

export default HTML
