// lingo3d-react/src/components/display/primitives/Cone.tsx
import React from "react"
import { Cone as GameCone } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { PrimitiveProps } from "../../../props/PrimitiveProps"

const Cone = React.forwardRef<GameCone, PrimitiveProps>((p, ref) => {
  const manager = useManager(p, ref, GameCone)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default Cone

// packages/lingo3d-vue/src/components/display/primitives/Cone.vue
<script setup lang="ts">
import { Cone } from "lingo3d"
import useManager from "../../../hooks/useManager"
import primitiveProps from "../../../props/primitiveProps"

const props = defineProps(primitiveProps)
const manager = useManager(props, Cone)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
