// lingo3d-react/src/components/display/primitives/Cube.tsx
import React from "react"
import { Cube as GameCube } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { PrimitiveProps } from "../../../props"

const Cube = React.forwardRef<GameCube, PrimitiveProps>((p, ref) => {
    const manager = useManager(p, ref, GameCube)
    return <ParentContext.Provider value={manager}>{p.children}</ParentContext.Provider>
})

export default Cube

// packages/lingo3d-vue/src/components/display/primitives/Cube.vue
<script setup lang="ts">
import { Cube } from "lingo3d"
import useManager from "../../../hooks/useManager"
import primitiveProps from "../../../props/primitiveProps"

const props = defineProps(primitiveProps)
const manager = useManager(props, Cube)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
