// lingo3d-vue/src/components/editor/Editor.vue
<script setup lang="ts">
import Editor from "lingo3d/lib/editor/Editor"
import { PropType } from "vue"
import useEditor from "../../hooks/useEditor"

const props = defineProps({
  mouse: {
    type: String as PropType<"enabled" | "disabled">,
    default: "disabled"
  },
  keyboard: {
    type: String as PropType<"enabled" | "disabled">,
    default: "disabled"
  }
})

const divRef = useEditor(Editor, props)
</script>

<template>
  <div ref="divRef" class="lingo3d-ui" style="height: 100%;" />
</template>

// lingo3d-react/src/components/editor/Editor.tsx
import React from "react"
import LingoEditor from "lingo3d/lib/editor/Editor"
import useEditor from "../../hooks/useEditor"

interface EditorProps {
  keyboard?: "enabled" | "disabled"
  mouse?: "enabled" | "disabled"
}

const Editor: React.FC<EditorProps> = (props) => {
  const divRef = useEditor(LingoEditor, props)

  return <div ref={divRef} className="lingo3d-ui" style={{ height: "100%" }} />
}

export default Editor
