// lingo3d-vue/src/components/editor/LingoEditor.vue
<script setup lang="ts">
import Editor from "./Editor.vue"
import Toolbar from "./Toolbar.vue"
import SceneGraph from "./SceneGraph.vue"
import Library from "./Library.vue"
import HUD from "./HUD.vue"
</script>

<template>
  <Toolbar />
  <SceneGraph />
  <Editor />
  <Library />
  <HUD />
</template>

// lingo3d-react/src/components/editor/LingoEditor.tsx
import React from "react"
import Toolbar from "./Toolbar"
import SceneGraph from "./SceneGraph"
import Editor from "./Editor"
import Library from "./Library"
import HUD from "./HUD"

const LingoEditor: React.FC = () => {
  return (
    <>
      <Toolbar />
      <SceneGraph />
      <Editor />
      <Library />
      <HUD />
    </>
  )
}

export default LingoEditor
