// lingo3d-react/src/components/display/lights/AmbientLight.tsx
import React from "react"
import { AmbientLight as GameAmbientLight } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { AmbientLightProps } from "../../../props"

const AmbientLight = React.forwardRef<GameAmbientLight, AmbientLightProps>((p, ref) => {
    const manager = useManager(p, ref, GameAmbientLight)
    return <ParentContext.Provider value={manager}>{p.children}</ParentContext.Provider>
})

export default AmbientLight

// lingo3d-vue/src/components/display/lights/AmbientLight.vue
<script lang="ts">
export default { inheritAttrs: false }
</script>
<script setup lang="ts">
import { AmbientLight } from "lingo3d"
import useManager from "../../../hooks/useManager"
import ambientLightProps from "../../../props/ambientLightProps"

const props = defineProps(ambientLightProps)
const manager = useManager(props, AmbientLight)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
