// lingo3d-react/src/components/display/lights/DirectionalLight.tsx
import React from "react"
import { DirectionalLight as GameDirectionalLight } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { DirectionalLightProps } from "../../../props"

const DirectionalLight = React.forwardRef<
  GameDirectionalLight,
  DirectionalLightProps
>((p, ref) => {
  const manager = useManager(p, ref, GameDirectionalLight)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default DirectionalLight

// lingo3d-vue/src/components/display/lights/DirectionalLight.vue
<script setup lang="ts">
import { DirectionalLight } from "lingo3d"
import useManager from "../../../hooks/useManager"
import directionalLightProps from "../../../props/directionalLightProps"

const props = defineProps(directionalLightProps)
const manager = useManager(props, DirectionalLight)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
