// lingo3d-react/src/components/display/lights/PointLight.tsx
import React from "react"
import { PointLight as GamePointLight } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { PointLightProps } from "../../../props/PointLightProps"

const PointLight = React.forwardRef<GamePointLight, PointLightProps>(
  (p, ref) => {
    const manager = useManager(p, ref, GamePointLight)
    return (
      <ParentContext.Provider value={manager}>
        {p.children}
      </ParentContext.Provider>
    )
  }
)

export default PointLight

// lingo3d-vue/src/components/display/lights/PointLight.vue
<script setup lang="ts">
import { PointLight } from "lingo3d"
import useManager from "../../../hooks/useManager"
import pointLightProps from "../../../props/pointLightProps"

const props = defineProps(pointLightProps)
const manager = useManager(props, PointLight)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
