// lingo3d-react/src/components/api/Keyboard.tsx
import React from "react"
import { Keyboard as GameKeyboard } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { KeyboardProps } from "../../props/KeyboardProps"

const Keyboard = React.forwardRef<GameKeyboard, KeyboardProps>((p, ref) => {
  const manager = useManager(p, ref, GameKeyboard)
  return <ParentContext.Provider value={manager} />
})
export default Keyboard

// lingo3d-vue/src/components/api/Keyboard.vue
<script setup lang="ts">
import { Keyboard } from "lingo3d"
import useManager from "../../hooks/useManager"
import keyboardProps from "../../props/keyboardProps"

const props = defineProps(keyboardProps)
const manager = useManager(props, Keyboard)
defineExpose(manager)
</script>

<template>
</template>
