// lingo3d-vue/src/components/display/Audio.vue
<script lang="ts">
export default { inheritAttrs: false }
</script>
<script setup lang="ts">
import { Audio } from "lingo3d"
import useManager from "../../hooks/useManager"
import audioProps from "../../props/audioProps"

const props = defineProps(audioProps)
const manager = useManager(props, Audio)
defineExpose(manager)
</script>

<template></template>

// lingo3d-react/src/components/display/Audio.tsx
import React from "react"
import { Audio as GameAudio } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { AudioProps } from "../../props"

const Audio = React.forwardRef<GameAudio, AudioProps>((p, ref) => {
  const manager = useManager(p, ref, GameAudio)
  return <ParentContext.Provider value={manager} />
})

export default Audio
