// lingo3d-vue/src/components/display/Environment.vue
<script setup lang="ts">
import { Environment } from "lingo3d"
import useManager from "../../hooks/useManager"
import environmentProps from "../../props/environmentProps"

const props = defineProps(environmentProps)
const manager = useManager(props, Environment)
defineExpose(manager)
</script>

<template></template>

// lingo3d-react/src/components/display/Environment.tsx
import React from "react"
import { Environment as GameEnvironment } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { EnvironmentProps } from "../../props"

const Environment = React.forwardRef<GameEnvironment, EnvironmentProps>(
  (p, ref) => {
    const manager = useManager(p, ref, GameEnvironment)
    return <ParentContext.Provider value={manager} />
  }
)

export default Environment
