// lingo3d-vue/src/components/display/Group.vue
<script lang="ts">
export default { inheritAttrs: false }
</script>
<script setup lang="ts">
import { Group } from "lingo3d"
import useManager from "../../hooks/useManager"
import groupProps from "../../props/groupProps"

const props = defineProps(groupProps)
const manager = useManager(props, Group)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/Group.tsx
import React from "react"
import { Group as GameGroup } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { GroupProps } from "../../props/GroupProps"

const Group = React.forwardRef<GameGroup, GroupProps>((p, ref) => {
  const manager = useManager(p, ref, GameGroup)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default Group
