// lingo3d-vue/src/components/display/HTMLMesh.vue
<script setup lang="ts">
import { HTMLMesh } from "lingo3d"
import { ref, toRaw, watchEffect } from "vue"
import useManager from "../../hooks/useManager"
import htmlMeshProps from "../../props/htmlMeshProps"

const props = defineProps(htmlMeshProps)
const manager = useManager(props, HTMLMesh)
defineExpose(manager)

const divRef = ref<HTMLDivElement>()
watchEffect(() => {
  manager.element = toRaw(divRef.value)
})
</script>

<template>
  <div ref="divRef">
    <slot />
  </div>
</template>

// lingo3d-react/src/components/display/HTMLMesh.tsx
import React, { useLayoutEffect, useRef } from "react"
import { HTMLMesh as GameHTMLMesh } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { HTMLMeshProps } from "../../props/HTMLMeshProps"

const HTMLMesh = React.forwardRef<GameHTMLMesh, HTMLMeshProps>((p, ref) => {
  const manager = useManager(p, ref, GameHTMLMesh)
  const divRef = useRef<HTMLDivElement>(null)

  useLayoutEffect(() => {
    manager.element = divRef.current
  }, [])

  return (
    <ParentContext.Provider value={manager}>
      <div ref={divRef}>{p.children}</div>
    </ParentContext.Provider>
  )
})

export default HTMLMesh
