// lingo3d-vue/src/components/display/Model.vue
<script setup lang="ts">
import { Model } from "lingo3d"
import useManager from "../../hooks/useManager"
import modelProps from "../../props/modelProps"

const props = defineProps(modelProps)
const manager = useManager(props, Model)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/Model.tsx
import React from "react"
import { Model as GameModel } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { ModelProps } from "../../props/ModelProps"

const Model = React.forwardRef<GameModel, ModelProps>((p, ref) => {
  const manager = useManager(p, ref, GameModel)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default Model
