// lingo3d-vue/src/components/display/RevoluteJoint.vue
<script setup lang="ts">
import { RevoluteJoint } from "lingo3d"
import useManager from "../../hooks/useManager"
import revoluteJointProps from "../../props/revoluteJointProps"

const props = defineProps(revoluteJointProps)
const manager = useManager(props, RevoluteJoint)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/RevoluteJoint.tsx
import React from "react"
import { RevoluteJoint as GameRevoluteJoint } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { RevoluteJointProps } from "../../props/RevoluteJointProps"

const RevoluteJoint = React.forwardRef<GameRevoluteJoint, RevoluteJointProps>(
  (p, ref) => {
    const manager = useManager(p, ref, GameRevoluteJoint)
    return (
      <ParentContext.Provider value={manager}>
        {p.children}
      </ParentContext.Provider>
    )
  }
)

export default RevoluteJoint
