// packages/lingo3d-vue/src/components/display/Skybox.vue
<script setup lang="ts">
import { Skybox } from "lingo3d"
import useManager from "../../hooks/useManager"
import skyboxProps from "../../props/skyboxProps"

const props = defineProps(skyboxProps)
const manager = useManager(props, Skybox)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/Skybox.tsx
import React from "react"
import { Skybox as GameSkybox } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { SkyboxProps } from "../../props/Skybox"

const Skybox = React.forwardRef<GameSkybox, SkyboxProps>((p, ref) => {
  const manager = useManager(p, ref, GameSkybox)
  return <ParentContext.Provider value={manager} />
})

export default Skybox
