// lingo3d-vue/src/components/display/SphericalJoint.vue
<script setup lang="ts">
import { SphericalJoint } from "lingo3d"
import useManager from "../../hooks/useManager"
import sphericalJointProps from "../../props/sphericalJointProps"

const props = defineProps(sphericalJointProps)
const manager = useManager(props, SphericalJoint)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/SphericalJoint.tsx
import React from "react"
import { SphericalJoint as GameSphericalJoint } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { SphericalJointProps } from "../../props/SphericalJointProps"

const SphericalJoint = React.forwardRef<
  GameSphericalJoint,
  SphericalJointProps
>((p, ref) => {
  const manager = useManager(p, ref, GameSphericalJoint)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default SphericalJoint
