// lingo3d-vue/src/components/display/TimelineAudio.vue
<script setup lang="ts">
import { TimelineAudio } from "lingo3d"
import useManager from "../../hooks/useManager"
import timelineAudioProps from "../../props/timelineAudioProps"

const props = defineProps(timelineAudioProps)
const manager = useManager(props, TimelineAudio)
defineExpose(manager)
</script>

<template>
  <slot />
</template>

// lingo3d-react/src/components/display/TimelineAudio.tsx
import React from "react"
import { TimelineAudio as GameTimelineAudio } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { TimelineAudioProps } from "../../props/TimelineAudioProps"

const TimelineAudio = React.forwardRef<GameTimelineAudio, TimelineAudioProps>((p, ref) => {
  const manager = useManager(p, ref, GameTimelineAudio)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default TimelineAudio
