// lingo3d-react/src/components/display/cameras/OrbitCamera.tsx
import React from "react"
import { OrbitCamera as GameOrbitCamera } from "lingo3d"
import useManager, { ParentContext } from "../../../hooks/useManager"
import { OrbitCameraProps } from "../../../props/OrbitCameraProps"

const OrbitCamera = React.forwardRef<GameOrbitCamera, OrbitCameraProps>(
  (p, ref) => {
    const manager = useManager(p, ref, GameOrbitCamera)
    return (
      <ParentContext.Provider value={manager}>
        {p.children}
      </ParentContext.Provider>
    )
  }
)

export default OrbitCamera

// lingo3d-vue/src/components/display/cameras/OrbitCamera.vue
<script setup lang="ts">
import { OrbitCamera } from "lingo3d"
import useManager from "../../../hooks/useManager"
import orbitCameraProps from "../../../props/orbitCameraProps"

const props = defineProps(orbitCameraProps)
const manager = useManager(props, OrbitCamera)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
