// lingo3d-vue/src/components/api/Mouse.vue
<script lang="ts">
export default { inheritAttrs: false }
</script>
<script setup lang="ts">
import { Mouse } from "lingo3d"
import useManager from "../../hooks/useManager"
import mouseProps from "../../props/mouseProps"

const props = defineProps(mouseProps)
const manager = useManager(props, Mouse)
defineExpose(manager)
</script>

<template></template>

// lingo3d-react/src/components/api/Mouse.tsx
import React from "react"
import { Mouse as GameMouse } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { MouseProps } from "../../props"

const Mouse = React.forwardRef<GameMouse, MouseProps>((p, ref) => {
    const manager = useManager(p, ref, GameMouse)
    return <ParentContext.Provider value={manager} />
})

export default Mouse
