// lingo3d-react/src/components/display/Scene.tsx
import React from "react"
import { Scene as GameScene } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { SceneProps } from "../../Props"

export const SceneContext = React.createContext<GameScene | undefined>(undefined)

const Scene = React.forwardRef<GameScene, SceneProps>((p, ref) => {
    const manager = useManager(p, ref, GameScene)
    return (
        <SceneContext.Provider value={manager}>
            <ParentContext.Provider value={manager}>
                {p.children}
            </ParentContext.Provider>
        </SceneContext.Provider>
    )
})

export default Scene

// packages/lingo3d-vue/src/components/display/Scene.vue
<script setup lang="ts">
import { Scene } from "lingo3d"
import useManager from "../../hooks/useManager"
import sceneProps from "../../props/sceneProps"

const props = defineProps(sceneProps)
const manager = useManager(props, Scene)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
