// lingo3d-react/src/components/display/Dummy.tsx
import React from "react"
import { Dummy as GameDummy } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { DummyProps } from "../../props"

const Dummy = React.forwardRef<GameDummy, DummyProps>((p, ref) => {
  const manager = useManager(p, ref, GameDummy)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default Dummy

// lingo3d-vue/src/components/display/Dummy.vue
<script setup lang="ts">
import { Dummy } from "lingo3d"
import useManager from "../../hooks/useManager"
import dummyProps from "../../props/dummyProps"

const props = defineProps(dummyProps)
const manager = useManager(props, Dummy)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
