// lingo3d-react/src/components/display/FixedJoint.tsx
import React from "react"
import { FixedJoint as GameFixedJoint } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { FixedJointProps } from "../../props/FixedJointProps"

const FixedJoint = React.forwardRef<GameFixedJoint, FixedJointProps>(
  (p, ref) => {
    const manager = useManager(p, ref, GameFixedJoint)
    return (
      <ParentContext.Provider value={manager}>
        {p.children}
      </ParentContext.Provider>
    )
  }
)

export default FixedJoint

// lingo3d-vue/src/components/display/FixedJoint.vue
<script setup lang="ts">
import { FixedJoint } from "lingo3d"
import useManager from "../../hooks/useManager"
import fixedJointProps from "../../props/fixedJointProps"

const props = defineProps(fixedJointProps)
const manager = useManager(props, FixedJoint)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
