// lingo3d-react/src/components/display/PrismaticJoint.tsx
import React from "react"
import { PrismaticJoint as GamePrismaticJoint } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { PrismaticJointProps } from "../../props/PrismaticJointProps"

const PrismaticJoint = React.forwardRef<
  GamePrismaticJoint,
  PrismaticJointProps
>((p, ref) => {
  const manager = useManager(p, ref, GamePrismaticJoint)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default PrismaticJoint

// lingo3d-vue/src/components/display/PrismaticJoint.vue
<script setup lang="ts">
import { PrismaticJoint } from "lingo3d"
import useManager from "../../hooks/useManager"
import prismaticJointProps from "../../props/prismaticJointProps"

const props = defineProps(prismaticJointProps)
const manager = useManager(props, PrismaticJoint)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
