// lingo3d-react/src/components/display/Reflector.tsx
import React from "react"
import { Reflector as GameReflector } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { ReflectorProps } from "../../props"

const Reflector = React.forwardRef<GameReflector, ReflectorProps>((p, ref) => {
    const manager = useManager(p, ref, GameReflector)
    return <ParentContext.Provider value={manager}>{p.children}</ParentContext.Provider>
})

export default Reflector

// lingo3d-vue/src/components/display/Reflector.vue
<script setup lang="ts">
import { Reflector } from "lingo3d"
import useManager from "../../hooks/useManager"
import reflectorProps from "../../props/reflectorProps"

const props = defineProps(reflectorProps)
const manager = useManager(props, Reflector)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
