// lingo3d-react/src/components/display/Setup.tsx
import React from "react"
import { Setup as GameSetup } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { SetupProps } from "../../props/SetupProps"

const Setup = React.forwardRef<GameSetup, SetupProps>((p, ref) => {
  const manager = useManager(p, ref, GameSetup)
  return <ParentContext.Provider value={manager} />
})

export default Setup

// lingo3d-vue/src/components/display/Setup.vue
<script lang="ts">
export default { inheritAttrs: false }
</script>
<script setup lang="ts">
import { Setup } from "lingo3d"
import useManager from "../../hooks/useManager"
import setupProps from "../../props/setupProps"

const props = defineProps(setupProps)
const manager = useManager(props, Setup)
defineExpose(manager)
</script>

<template></template>
