// lingo3d-react/src/components/display/SpawnPoint.tsx
import React from "react"
import { SpawnPoint as GameSpawnPoint } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { SpawnPointProps } from "../../props"

const SpawnPoint = React.forwardRef<GameSpawnPoint, SpawnPointProps>(
  (p, ref) => {
    const manager = useManager(p, ref, GameSpawnPoint)
    return (
      <ParentContext.Provider value={manager}>
        {p.children}
      </ParentContext.Provider>
    )
  }
)

export default SpawnPoint

// lingo3d-vue/src/components/display/SpawnPoint.vue
<script setup lang="ts">
import { SpawnPoint } from "lingo3d"
import useManager from "../../hooks/useManager"
import spawnPointProps from "../../props/spawnPointProps"

const props = defineProps(spawnPointProps)
const manager = useManager(props, SpawnPoint)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
