// lingo3d-react/src/components/display/SpriteSheet.tsx
import React from "react"
import { SpriteSheet as GameSpriteSheet } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { SpriteSheetProps } from "../../props/SpriteSheetProps"

const SpriteSheet = React.forwardRef<GameSpriteSheet, SpriteSheetProps>((p, ref) => {
  const manager = useManager(p, ref, GameSpriteSheet)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default SpriteSheet

// lingo3d-vue/src/components/display/SpriteSheet.vue
<script setup lang="ts">
import { SpriteSheet } from "lingo3d"
import useManager from "../../hooks/useManager"
import spriteSheetProps from "../../props/spriteSheetProps"

const props = defineProps(spriteSheetProps)
const manager = useManager(props, SpriteSheet)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
