// lingo3d-react/src/components/display/Sprite.tsx
import React from "react"
import { Sprite as GameSprite } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { SpriteProps } from "../../props"

const Sprite = React.forwardRef<GameSprite, SpriteProps>((p, ref) => {
    const manager = useManager(p, ref, GameSprite)
    return <ParentContext.Provider value={manager}>{p.children}</ParentContext.Provider>
})

export default Sprite

// lingo3d-vue/src/components/display/Sprite.vue
<script lang="ts">
export default { inheritAttrs: false }
</script>
<script setup lang="ts">
import { Sprite } from "lingo3d"
import useManager from "../../hooks/useManager"
import spriteProps from "../../props/spriteProps"

const props = defineProps(spriteProps)
const manager = useManager(props, Sprite)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
