// lingo3d-react/src/components/display/Timeline.tsx
import React from "react"
import { Timeline as GameTimeline } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { TimelineProps } from "../../props/TimelineProps"

const Timeline = React.forwardRef<GameTimeline, TimelineProps>((p, ref) => {
  const manager = useManager(p, ref, GameTimeline)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default Timeline

// lingo3d-vue/src/components/display/Timeline.vue
<script setup lang="ts">
import { Timeline } from "lingo3d"
import useManager from "../../hooks/useManager"
import timelineProps from "../../props/timelineProps"

const props = defineProps(timelineProps)
const manager = useManager(props, Timeline)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
