// lingo3d-react/src/components/display/Water.tsx
import React from "react"
import { Water as GameWater } from "lingo3d"
import useManager, { ParentContext } from "../../hooks/useManager"
import { WaterProps } from "../../props"

const Water = React.forwardRef<GameWater, WaterProps>((p, ref) => {
  const manager = useManager(p, ref, GameWater)
  return (
    <ParentContext.Provider value={manager}>
      {p.children}
    </ParentContext.Provider>
  )
})

export default Water

// lingo3d-vue/src/components/display/Water.vue
<script setup lang="ts">
import { Water } from "lingo3d"
import useManager from "../../hooks/useManager"
import waterProps from "../../props/waterProps"

const props = defineProps(waterProps)
const manager = useManager(props, Water)
defineExpose(manager)
</script>

<template>
  <slot />
</template>
